CORE_SAMPLES_PATH: data\core_samples_raw.csv
SEM_SAMPLES_PATH: data\sem_samples_raw.csv
MT_SAMPLES_PATH: data\mt_samples_raw.csv
SNN_SAMPLES_PATH: data\snn_samples_raw.csv
SYNONYMS_PATH: data\synonyms_250325_reduced.csv
AUG_FULL_CSV_PATH: data\aug_full.csv 
AUG_SYNTH_CSV_PATH: data\aug_synth.csv
SUBSAMPLE_FULL_CSV_PATH: data\subsample_full.csv
SUBSAMPLE_SYNTH_CSV_PATH: data\subsample_synth.csv
METADATA_FULL_CSV_PATH: data\metadata_full_18052025.csv
METADATA_SYNTH_CSV_PATH: data\metadata_synth_18052025.csv
H5_SAMPLE_DIM_CHUNK_SIZE: 512
H5_COMPRESSION: lzf
H5_COMPRESSION_LEVEL: 7
CACHE_SIZE_MB: 4000
CACHE_SLOTS: 128
CACHE_POLICY: 0.5
MT_SNN_VAL_SAMPLES: 800
MT_SNN_TEST_SAMPLES: 800
SHAPENET_VAL_SAMPLES: 800
SHAPENET_TEST_SAMPLES: 800
GLOBAL_SAMPLES_COUNT: 80000
GLOBAL_SAMPLES_SYNTH_COUNT: 40000
SAMPLED_POINTS: 10000
AUGMENTATION_RADIUS: 0.75
AUGMENTATION_STD: 0.01