training:
  NUM_EPOCH: 300
  BATCH_SIZE: 128
  LEARNING_RATE: 1e-4
  WEIGHT_DECAY: 1e-6
  SCHEDULER_STEP: 60
  SCHEDULER_GAMMA: 0.5

model:
  DECODER_PE_TYPE: grid
  LATENT_DIM: 512
  LATENT_DIM_ROTATION: 32
  R: 45
  GRID_VALUES_MAX: 0.3
  K_DIFF: 7.5
  K_GCN: 16
  CHEBY_ORDER: 3
  FILM_K: 0.7
  TE_HEADS: 2
  TE_LAYERS: 1

loss:
  L_CD: 1.0
  L_CONTRASTIVE: 1.0
  L_ROTATION: 1.0
  TEMPERATURE: 0.2
  NTXENT_SIG_SCALE: 3
  NTXENT_SIG_SHIFT: -2.5
  D_MAX: 0.2
  CD_IOU_SUBSAMPLE_POINTS: 128